FROM arm32v6/python:3.9-alpine

ENV PYTHONUNBUFFERED=1

# Installa dipendenze necessarie
RUN apk add --no-cache \
    docker-cli \
    curl \
    ca-certificates \
    gnupg

# Installa paho-mqtt
RUN pip install --no-cache-dir paho-mqtt

WORKDIR /app
COPY src/docker2mqttenh.py /app/
RUN chmod +x /app/docker2mqttenh.py

ENTRYPOINT ["python3", "/app/docker2mqttenh.py"]